// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates a summarized description of each plant species identified in an image.
 *
 * - generateSpeciesSummary - A function that generates a summary of plant species.
 * - GenerateSpeciesSummaryInput - The input type for the generateSpeciesSummary function.
 * - GenerateSpeciesSummaryOutput - The return type for the generateSpeciesSummary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateSpeciesSummaryInputSchema = z.object({
  speciesList: z
    .string()
    .describe("A comma separated list of plant species identified in the image."),
});
export type GenerateSpeciesSummaryInput = z.infer<typeof GenerateSpeciesSummaryInputSchema>;

const GenerateSpeciesSummaryOutputSchema = z.object({
  summaries: z.array(
    z.object({
      species: z.string().describe('The name of the plant species.'),
      summary: z.string().describe('A short summary of the plant species.'),
    })
  ),
});
export type GenerateSpeciesSummaryOutput = z.infer<typeof GenerateSpeciesSummaryOutputSchema>;

export async function generateSpeciesSummary(input: GenerateSpeciesSummaryInput): Promise<GenerateSpeciesSummaryOutput> {
  return generateSpeciesSummaryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateSpeciesSummaryPrompt',
  input: {schema: GenerateSpeciesSummaryInputSchema},
  output: {schema: GenerateSpeciesSummaryOutputSchema},
  prompt: `You are an expert botanist. Generate a short summary for each plant species in the following list: {{{speciesList}}}. Return a JSON array of species and summary objects.`,
});

const generateSpeciesSummaryFlow = ai.defineFlow(
  {
    name: 'generateSpeciesSummaryFlow',
    inputSchema: GenerateSpeciesSummaryInputSchema,
    outputSchema: GenerateSpeciesSummaryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
